services:
  clickhouse_db:
    container_name: clickhouse_db
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./dataset:/var/lib/clickhouse/user_files
      # - ./clickhouse-server:/etc/clickhouse-server
    env_file:
      - ./config/clickhouse_db.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - coffee_network
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./config/metabase.env
    depends_on:
      - metabase_db
      - clickhouse_db
    volumes:
      - metabase-data:/metabase-data
      - ~/metabase/plugins:/plugins
    networks:
      - coffee_network
  metabase_db:
    image: postgres:latest
    container_name: metabase_db
    restart: always
    env_file:
      - ./config/metabase_db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coffee_network

  postgres: # database for airflow to store metadata etc.
    image: postgres:latest
    networks:
      - coffee_network
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  init-airflow: # to initialize user / admin and database for airflow
    image: apache/airflow:latest
    depends_on:
      - postgres
    networks:
      - coffee_network
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db migrate && airflow connections create-default-connections && airflow users create --username airflow --password password --firstname John --lastname Doe --role Admin --email admin@example.com"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - coffee_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingestion_script:/opt/ingestion_script
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD=password
      - AIRFLOW__WWW__USER_USERNAME=airflow
      - AIRFLOW__WWW__USER_PASSWORD=password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    env_file:
      - ./config/airflow.env
    ports:
      - "8080:8080"
    command: webserver
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - coffee_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ingestion_script:/opt/ingestion_script
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD=password
      - AIRFLOW__WWW__USER_USERNAME=airflow
      - AIRFLOW__WWW__USER_PASSWORD=password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    env_file:
      - ./config/airflow.env
    command: scheduler

volumes:
  metabase-data:
  postgres-data:
  clickhouse-data:

networks:
  coffee_network:
    driver: bridge
