services:
  clickhouse_db:
    container_name: clickhouse_db
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./dataset:/var/lib/clickhouse/user_files
      # - ./clickhouse-server:/etc/clickhouse-server
    env_file:
      - ./config/clickhouse_db.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - coffee_network
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./config/metabase.env
    depends_on:
      - metabase_db
      - clickhouse_db
    volumes:
      - metabase-data:/metabase-data
      - ~/metabase/plugins:/plugins
    networks:
      - coffee_network
  metabase_db:
    image: postgres:latest
    container_name: metabase_db
    restart: always
    env_file:
      - ./config/metabase_db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coffee_network

volumes:
  metabase-data:
  postgres-data:
  clickhouse-data:

networks:
  coffee_network:
    driver: bridge
